### ISSUE TITLE
Error thrown on startup

### ISSUE THREAD

**Issue by Conner-Anderson** [Conner-Anderson/discord-hvz#55]
Sometimes when the bot launches, this error is thrown:

`Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\conne\Dev\discord-hvz-live\venv\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\conne\Dev\discord-hvz-live\discord_hvz.py", line 106, in inner
    my_guild_id = self.guild.id
AttributeError: 'NoneType' object has no attribute 'id'`

This is probably because another event is firing before the on_ready event, and the check_event decorator needs information that is set during on_ready to work. This bug causes no issues besides the annoying log I believe.

**Comment by Conner-Anderson** [comment]
A pycord update fixed this.
